### ISSUE TITLE
Agree on a top-level problem statement with key stakeholders in order to create a defined baseline going into UR Discovery.

### ISSUE THREAD

**Issue by PaulChapmanPM** [NHSDigital/Value-Set#21]
Agree on the problem statement with key stakeholders in order to create a defined baseline going into UR Discovery.

D.O.D.
- Problem statement agreed with Tracy Simmonite, Pete Turnbull, Ian Ramsey and Nicholas Oughtibridge (as a minimum)

**Comment by alanpnhs** [comment]
Problem statement(s) are available from existing reports (eg from SNOMED Implementation Team, PRSB, Faculty of Clinical Informatics etc). These will be distilled into those that we are looking to mitigate and then these agreed problems will be mapped to the Capabilities - to show (where possible) which capability will 'resolve/minimise' the problem.

**Comment by PaulChapmanPM** [comment]
With Pete T for review
