### ISSUE TITLE
Refine comms draft and create new comms for specific user groups

### ISSUE THREAD

**Issue by kobi44** [NHSDigital/Value-Set#26]
Refine comms draft and create new comms for specific user groups

D.O.D. 
- Comms wording agreed with Tracy Simmonite, Alan Payne, with input from other SMEs in SNOMED Implementation team.

**Comment by PaulChapmanPM** [comment]
Drafts complete. To be shared with Tracy for review.

**Comment by PaulChapmanPM** [comment]
Done
