### ISSUE TITLE
Issue UR recruitment survey through the Terminology & Classifications Newsletter

### ISSUE THREAD

**Issue by PaulChapmanPM** [NHSDigital/Value-Set#47]
Send the UR Survey to the agreed set of initial Terminology & Classification newsletter recipients.
D.o.D.
- Survey issued to Terminology & Classification newsletter recipients

**Comment by alanpnhs** [comment]
Issued to T&C newsletter Team. 

T&C Newsletter (targeted 30th August)
Industry Liason 
- has a distribution List (Tech UK) - give wording and link, then IL will create mailing list (awaiting confirmation that wording before handing wording to IL) 
- Tech UK (Bulletin) - same wording to go into a Bulletin

**Comment by PaulChapmanPM** [comment]
Newsletter was delayed so our survey was sent out to the newsletter recipients as a separate email.
