### ISSUE TITLE
Promote survey in T&C Newsletter article. 2,500 recipients (30 Sept)

### ISSUE THREAD

**Issue by PeterGarrett-SNOMED** [NHSDigital/Value-Set#50]
In order to promote the survey
I will write some promotion material for the T&C Quarterly newsletter

DOD
- Agreed and approved Communications [Done]
- sent to T&C business admin by 8th August [Done]
- Published in the September newsletter 22 September  [DONE]
 
Link
https://hscic365.sharepoint.com/:w:/r/sites/ValueSetPlatform/Shared%20Documents/General/Marketing%20and%20Comms/Value%20Sets-%20T%26C%20Newsletter-Aug2022.docx?d=wc85a7ebf007445fe986ef55618531eff&csf=1&web=1

**Comment by alanpnhs** [comment]
Content with the T&C Newsletter people for issuing on the next issue

**Comment by PaulChapmanPM** [comment]
Done
